name: Publish the Gatsby Site

on:
  push:
    branches: [development]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.TOKEN_GITHUB }}
          deploy-branch: master
          gatsby-args: "--version"
